[build]
  base = "site"              # the subdirectory containing the chatbot site
  publish = "."           # for plain static site (index.html inside /swsr site)
  command = ""

  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF site/ netlify.toml"
