[build]       
  base = "site"
  publish = "."              # for plain static site (index.html inside /site)
  command = ""

ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF site/ netlify.toml"
